defaultNamespace: redis
helm:
  releaseName: redis
  chart: oci://dp.apps.rancher.io/charts/redis
  version: 0.2.1

diff:
  comparePatches:
  - apiVersion: apps/v1
    kind: StatefulSet
    name: redis
    namespace: redis
    operations:
    - {"op": "remove", "path":"/spec"}
